//go:build integration

package emailsubscriptions

import (
	"context"
	"database/sql"
	"os"
	"path/filepath"
	"strings"
	"testing"

	_ "github.com/mattn/go-sqlite3"
	"github.com/stretchr/testify/require"
)

func TestSQLStore_WithModuleMigration_EndToEnd(t *testing.T) {
	dbPath := filepath.Join(t.TempDir(), "emailsubscriptions-integration.db")
	db, err := sql.Open("sqlite3", dbPath)
	require.NoError(t, err)
	t.Cleanup(func() { _ = db.Close() })

	applyModuleMigration(t, db)

	ctx := context.Background()
	store := NewSQLStore(db, "sqlite3")
	service := NewServiceWithVerifier(store, func(string) error { return nil })

	list := List("newsletter")
	require.NoError(t, service.CreateList(ctx, list))

	sub, err := service.Subscribe(ctx, "alice@example.com", list, nil, nil)
	require.NoError(t, err)
	require.NotEmpty(t, sub.ConfirmationCode)
	require.False(t, sub.Verified)

	require.NoError(t, service.Confirm(ctx, sub.ConfirmationCode))
	// legacy no-token unsubscribe path remains supported
	require.NoError(t, service.Unsubscribe(ctx, "alice@example.com", "", list))

	sub, err = service.Subscribe(ctx, "alice@example.com", list, nil, nil)
	require.NoError(t, err)
	require.NoError(t, service.Unsubscribe(ctx, "alice@example.com", sub.ConfirmationCode, list))
}

func applyModuleMigration(t *testing.T, db *sql.DB) {
	t.Helper()

	migrationPath := filepath.Join("db", "migrate", "migrations", "20260305170000_init_email_subscriptions.sql")
	migrationBytes, err := os.ReadFile(migrationPath)
	require.NoError(t, err)

	upSQL := sqliteCompatibleDDL(extractGooseUp(string(migrationBytes)))
	_, err = db.Exec(upSQL)
	require.NoError(t, err)
}

func extractGooseUp(content string) string {
	lines := strings.Split(content, "\n")
	var builder strings.Builder
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		switch trimmed {
		case "-- +goose Up":
			continue
		case "-- +goose Down":
			return builder.String()
		default:
			builder.WriteString(line)
			builder.WriteString("\n")
		}
	}
	return builder.String()
}

func sqliteCompatibleDDL(v string) string {
	replacements := []struct {
		old string
		new string
	}{
		{"BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", "INTEGER PRIMARY KEY AUTOINCREMENT"},
		{"TIMESTAMPTZ", "DATETIME"},
		{"DOUBLE PRECISION", "REAL"},
		{"VARCHAR", "TEXT"},
	}
	out := v
	for _, replacement := range replacements {
		out = strings.ReplaceAll(out, replacement.old, replacement.new)
	}
	return out
}
