# Name of your application. Used to uniquely configure containers.
service: goship

# Name of the container image.
image: leomorpho/goship

# ssh:
#   log_level: debug

# Deploy to these servers.
servers:
  - 134.199.211.26
 
# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    PAGODA_APP_PAGESIZE: 15
    PAGODA_HTTP_PORT: 8000
    PAGODA_HTTP_DOMAIN: "https://goship.run"
    PAGODA_APP_ENVIRONMENT: "prod"
    PAGODA_APP_OPERATIONALCONSTANTS_USERSIGNUPENABLED: "true"
    PAGODA_APP_OPERATIONALCONSTANTS_PAYMENTSENABLED: "false" 
    PAGODA_APP_OPERATIONALCONSTANTS_PRODUCTPROCODE: "price_..."
    PAGODA_HTTP_HOSTNAME: "0.0.0.0"
    PAGODA_CACHE_HOSTNAME: "10.124.0.2"
    PAGODA_CACHE_PORT: 6379
    PAGODA_CACHE_DATABASE: "2" # Sharing with eclair and Cherie, which use 1 & 2
    PAGODA_MAIL_SMTPPORT: 1025
    PAGODA_STORAGE_APPBUCKETNAME: "FILL"
    PAGODA_CACHE_EXPIRATIONPAGE: "2h"
    PAGODA_CACHE_EXPIRATIONSTATICFILE: "4380h"
    PAGODA_MAIL_FROMADDRESS: "cherie@chatbond.app"
    PAGODA_APP_SUPPORTEMAIL: "cherie@chatbond.app"

  secret:
    - PAGODA_APP_ENCRYPTIONKEY

proxy:
  app_port: 8000
  ssl: false
  host: goship.run
  forward_headers: true
  buffering:
    requests: false
    responses: false
