// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/invitation"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/profile"
)

// InvitationUpdate is the builder for updating Invitation entities.
type InvitationUpdate struct {
	config
	hooks    []Hook
	mutation *InvitationMutation
}

// Where appends a list predicates to the InvitationUpdate builder.
func (iu *InvitationUpdate) Where(ps ...predicate.Invitation) *InvitationUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetUpdatedAt sets the "updated_at" field.
func (iu *InvitationUpdate) SetUpdatedAt(t time.Time) *InvitationUpdate {
	iu.mutation.SetUpdatedAt(t)
	return iu
}

// SetInviteeName sets the "invitee_name" field.
func (iu *InvitationUpdate) SetInviteeName(s string) *InvitationUpdate {
	iu.mutation.SetInviteeName(s)
	return iu
}

// SetNillableInviteeName sets the "invitee_name" field if the given value is not nil.
func (iu *InvitationUpdate) SetNillableInviteeName(s *string) *InvitationUpdate {
	if s != nil {
		iu.SetInviteeName(*s)
	}
	return iu
}

// SetConfirmationCode sets the "confirmation_code" field.
func (iu *InvitationUpdate) SetConfirmationCode(s string) *InvitationUpdate {
	iu.mutation.SetConfirmationCode(s)
	return iu
}

// SetNillableConfirmationCode sets the "confirmation_code" field if the given value is not nil.
func (iu *InvitationUpdate) SetNillableConfirmationCode(s *string) *InvitationUpdate {
	if s != nil {
		iu.SetConfirmationCode(*s)
	}
	return iu
}

// SetInviterID sets the "inviter" edge to the Profile entity by ID.
func (iu *InvitationUpdate) SetInviterID(id int) *InvitationUpdate {
	iu.mutation.SetInviterID(id)
	return iu
}

// SetInviter sets the "inviter" edge to the Profile entity.
func (iu *InvitationUpdate) SetInviter(p *Profile) *InvitationUpdate {
	return iu.SetInviterID(p.ID)
}

// Mutation returns the InvitationMutation object of the builder.
func (iu *InvitationUpdate) Mutation() *InvitationMutation {
	return iu.mutation
}

// ClearInviter clears the "inviter" edge to the Profile entity.
func (iu *InvitationUpdate) ClearInviter() *InvitationUpdate {
	iu.mutation.ClearInviter()
	return iu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *InvitationUpdate) Save(ctx context.Context) (int, error) {
	iu.defaults()
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *InvitationUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *InvitationUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *InvitationUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iu *InvitationUpdate) defaults() {
	if _, ok := iu.mutation.UpdatedAt(); !ok {
		v := invitation.UpdateDefaultUpdatedAt()
		iu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *InvitationUpdate) check() error {
	if v, ok := iu.mutation.InviteeName(); ok {
		if err := invitation.InviteeNameValidator(v); err != nil {
			return &ValidationError{Name: "invitee_name", err: fmt.Errorf(`ent: validator failed for field "Invitation.invitee_name": %w`, err)}
		}
	}
	if v, ok := iu.mutation.ConfirmationCode(); ok {
		if err := invitation.ConfirmationCodeValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_code", err: fmt.Errorf(`ent: validator failed for field "Invitation.confirmation_code": %w`, err)}
		}
	}
	if iu.mutation.InviterCleared() && len(iu.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.inviter"`)
	}
	return nil
}

func (iu *InvitationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.InviteeName(); ok {
		_spec.SetField(invitation.FieldInviteeName, field.TypeString, value)
	}
	if value, ok := iu.mutation.ConfirmationCode(); ok {
		_spec.SetField(invitation.FieldConfirmationCode, field.TypeString, value)
	}
	if iu.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// InvitationUpdateOne is the builder for updating a single Invitation entity.
type InvitationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InvitationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (iuo *InvitationUpdateOne) SetUpdatedAt(t time.Time) *InvitationUpdateOne {
	iuo.mutation.SetUpdatedAt(t)
	return iuo
}

// SetInviteeName sets the "invitee_name" field.
func (iuo *InvitationUpdateOne) SetInviteeName(s string) *InvitationUpdateOne {
	iuo.mutation.SetInviteeName(s)
	return iuo
}

// SetNillableInviteeName sets the "invitee_name" field if the given value is not nil.
func (iuo *InvitationUpdateOne) SetNillableInviteeName(s *string) *InvitationUpdateOne {
	if s != nil {
		iuo.SetInviteeName(*s)
	}
	return iuo
}

// SetConfirmationCode sets the "confirmation_code" field.
func (iuo *InvitationUpdateOne) SetConfirmationCode(s string) *InvitationUpdateOne {
	iuo.mutation.SetConfirmationCode(s)
	return iuo
}

// SetNillableConfirmationCode sets the "confirmation_code" field if the given value is not nil.
func (iuo *InvitationUpdateOne) SetNillableConfirmationCode(s *string) *InvitationUpdateOne {
	if s != nil {
		iuo.SetConfirmationCode(*s)
	}
	return iuo
}

// SetInviterID sets the "inviter" edge to the Profile entity by ID.
func (iuo *InvitationUpdateOne) SetInviterID(id int) *InvitationUpdateOne {
	iuo.mutation.SetInviterID(id)
	return iuo
}

// SetInviter sets the "inviter" edge to the Profile entity.
func (iuo *InvitationUpdateOne) SetInviter(p *Profile) *InvitationUpdateOne {
	return iuo.SetInviterID(p.ID)
}

// Mutation returns the InvitationMutation object of the builder.
func (iuo *InvitationUpdateOne) Mutation() *InvitationMutation {
	return iuo.mutation
}

// ClearInviter clears the "inviter" edge to the Profile entity.
func (iuo *InvitationUpdateOne) ClearInviter() *InvitationUpdateOne {
	iuo.mutation.ClearInviter()
	return iuo
}

// Where appends a list predicates to the InvitationUpdate builder.
func (iuo *InvitationUpdateOne) Where(ps ...predicate.Invitation) *InvitationUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *InvitationUpdateOne) Select(field string, fields ...string) *InvitationUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Invitation entity.
func (iuo *InvitationUpdateOne) Save(ctx context.Context) (*Invitation, error) {
	iuo.defaults()
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *InvitationUpdateOne) SaveX(ctx context.Context) *Invitation {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *InvitationUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *InvitationUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (iuo *InvitationUpdateOne) defaults() {
	if _, ok := iuo.mutation.UpdatedAt(); !ok {
		v := invitation.UpdateDefaultUpdatedAt()
		iuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *InvitationUpdateOne) check() error {
	if v, ok := iuo.mutation.InviteeName(); ok {
		if err := invitation.InviteeNameValidator(v); err != nil {
			return &ValidationError{Name: "invitee_name", err: fmt.Errorf(`ent: validator failed for field "Invitation.invitee_name": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.ConfirmationCode(); ok {
		if err := invitation.ConfirmationCodeValidator(v); err != nil {
			return &ValidationError{Name: "confirmation_code", err: fmt.Errorf(`ent: validator failed for field "Invitation.confirmation_code": %w`, err)}
		}
	}
	if iuo.mutation.InviterCleared() && len(iuo.mutation.InviterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invitation.inviter"`)
	}
	return nil
}

func (iuo *InvitationUpdateOne) sqlSave(ctx context.Context) (_node *Invitation, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invitation.Table, invitation.Columns, sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeInt))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invitation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invitation.FieldID)
		for _, f := range fields {
			if !invitation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invitation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.UpdatedAt(); ok {
		_spec.SetField(invitation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.InviteeName(); ok {
		_spec.SetField(invitation.FieldInviteeName, field.TypeString, value)
	}
	if value, ok := iuo.mutation.ConfirmationCode(); ok {
		_spec.SetField(invitation.FieldConfirmationCode, field.TypeString, value)
	}
	if iuo.mutation.InviterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invitation.InviterTable,
			Columns: []string{invitation.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invitation{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invitation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
