// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mikestefanello/pagoda/ent/predicate"
	"github.com/mikestefanello/pagoda/ent/pwapushsubscription"
)

// PwaPushSubscriptionDelete is the builder for deleting a PwaPushSubscription entity.
type PwaPushSubscriptionDelete struct {
	config
	hooks    []Hook
	mutation *PwaPushSubscriptionMutation
}

// Where appends a list predicates to the PwaPushSubscriptionDelete builder.
func (ppsd *PwaPushSubscriptionDelete) Where(ps ...predicate.PwaPushSubscription) *PwaPushSubscriptionDelete {
	ppsd.mutation.Where(ps...)
	return ppsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ppsd *PwaPushSubscriptionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ppsd.sqlExec, ppsd.mutation, ppsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ppsd *PwaPushSubscriptionDelete) ExecX(ctx context.Context) int {
	n, err := ppsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ppsd *PwaPushSubscriptionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pwapushsubscription.Table, sqlgraph.NewFieldSpec(pwapushsubscription.FieldID, field.TypeInt))
	if ps := ppsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ppsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ppsd.mutation.done = true
	return affected, err
}

// PwaPushSubscriptionDeleteOne is the builder for deleting a single PwaPushSubscription entity.
type PwaPushSubscriptionDeleteOne struct {
	ppsd *PwaPushSubscriptionDelete
}

// Where appends a list predicates to the PwaPushSubscriptionDelete builder.
func (ppsdo *PwaPushSubscriptionDeleteOne) Where(ps ...predicate.PwaPushSubscription) *PwaPushSubscriptionDeleteOne {
	ppsdo.ppsd.mutation.Where(ps...)
	return ppsdo
}

// Exec executes the deletion query.
func (ppsdo *PwaPushSubscriptionDeleteOne) Exec(ctx context.Context) error {
	n, err := ppsdo.ppsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pwapushsubscription.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ppsdo *PwaPushSubscriptionDeleteOne) ExecX(ctx context.Context) {
	if err := ppsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
