package routenames

const (
	RouteNameForgotPassword          = "forgot_password"
	RouteNameForgotPasswordSubmit    = "forgot_password.submit"
	RouteNameLogin                   = "login"
	RouteNameLoginSubmit             = "login.submit"
	RouteNameOAuthStart              = "oauth.start"
	RouteNameOAuthCallback           = "oauth.callback"
	RouteNameTwoFactorVerify         = "two_factor.verify"
	RouteNameTwoFactorVerifySubmit   = "two_factor.verify.submit"
	RouteNameLogout                  = "logout"
	RouteNameRegister                = "register"
	RouteNameRegisterSubmit          = "register.submit"
	RouteNameResetPassword           = "reset_password"
	RouteNameResetPasswordSubmit     = "reset_password.submit"
	RouteNameVerifyEmail             = "verify_email"
	RouteNameLandingPage             = "landing_page"
	RouteNamePreferences             = "preferences"
	RouteNameTwoFactorSetup          = "two_factor.setup"
	RouteNameTwoFactorSetupSubmit    = "two_factor.setup.submit"
	RouteNameTwoFactorBackupCodes    = "two_factor.backup_codes"
	RouteNameGetPhone                = "phone.get"
	RouteNameUpdatePhoneNum          = "phone.save"
	RouteNameGetDisplayName          = "display_name.get"
	RouteNameUpdateDisplayName       = "display_name.save"
	RouteNameGetPhoneVerification    = "phone.verification"
	RouteNameSubmitPhoneVerification = "phone.verification.submit"
	RouteNameDeleteAccountPage       = "delete_account.page"
	RouteNameDeleteAccountRequest    = "delete_account.request"
	RouteNameAIDemo                  = "ai_demo"
	RouteNameAIDemoStream            = "ai_demo.stream"
	RouteNameSharedCounter           = "shared_counter"
	RouteNameSharedCounterStream     = "shared_counter.stream"
	RouteNameSharedCounterIncrement  = "shared_counter.increment"
	RouteNameIslandsDemo             = "islands_demo"

	RouteNameHomeFeed           = "home_feed"
	RouteNameGetHomeFeedButtons = "home_feed.buttons"
	RouteNameGetHomeFeedStats   = "home_feed.stats"

	RouteNameProfile                   = "profile"
	RouteNameInstallApp                = "install_app"
	RouteNameClearCookie               = "clear_cookie"
	RouteNameHealthcheck               = "healthcheck"
	RouteNameHealthLiveness            = "health.liveness"
	RouteNameHealthReadiness           = "health.readiness"
	RouteNameMailPreviewIndex          = "mail_preview.index"
	RouteNameMailPreviewWelcome        = "mail_preview.welcome"
	RouteNameMailPreviewPasswordReset  = "mail_preview.password_reset"
	RouteNameMailPreviewVerifyEmail    = "mail_preview.verify_email"
	RouteNameEmailSubscribe            = "email_subscribe"
	RouteNameEmailSubscribeSubmit      = "email_subscribe.submit"
	RouteNameVerifyEmailSubscription   = "verify_email_subscription"
	RouteNameUploadPhoto               = "upload_photo"
	RouteNameUploadPhotoSubmit         = "upload_photo.submit"
	RouteNameUploadPhotoDelete         = "upload_photo.delete"
	RouteNameCurrentProfilePhoto       = "current_profile_photo"
	RouteNameCurrentProfilePhotoSubmit = "current_profile_photo.submit"
	RouteNameNotifications             = "notifications"
	RouteNameDeleteNotification        = "notifications.delete"
	RouteNameNormalNotificationsCount  = "normal_notifications_count"

	RouteNameMarkNotificationsAsRead    = "markNormalNotificationRead"
	RouteNameMarkNotificationsAsUnread  = "notifications.unread"
	RouteNameMarkAllNotificationsAsRead = "normalNotificationsMarkAllAsRead"

	RouteNameRealtime = "realtime"

	RouteNameFinishOnboarding = "finish_onboarding"
	RouteNameGetBio           = "profileBio.get"
	RouteNameUpdateBio        = "profileBio.post"

	RouteNameGetPushSubscriptions             = "push_subscriptions.get"
	RouteNameRegisterSubscription             = "notification_subscriptions.register"
	RouteNameDeleteSubscription               = "notification_subscriptions.delete"
	RouteNameDeleteEmailSubscriptionWithToken = "email_subscriptions.delete_with_token"

	RouteNamePaymentProcessorGetPublicKey = "payment_processor.get_public_key"
	RouteNameCreateCheckoutSession        = "stripe.create_checkout_session"
	RouteNameCreatePortalSession          = "stripe.create_portal_session"
	RouteNamePaymentProcessorWebhook      = "stripe.webhook"
	RouteNamePricingPage                  = "pricing_page"
	RouteNamePaymentProcessorSuccess      = "stripe.success"
	RouteNameManagedStatus                = "managed.status"
	RouteNameManagedBackup                = "managed.backup"
	RouteNameManagedRestore               = "managed.restore"
)
