// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/mikestefanello/pagoda/pkg/types"
)

/*
HeatmapComponent is a component that displays a heatmap of the number of interactions per day. It is used in Chérie Companion App
but not in Goship. Left here for reference. It needs to consume the countsByDay slice of types.CountByDay.
*/

func HeatmapComponent(countsByDay []types.CountByDay) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\" w-screen md:w-full md:overflow-hidden\"><div id=\"horizontal-scroll-container\" class=\"flex flex-col justify-center items-center p-4 w-full overflow-x-auto h-min\"><div id=\"cal-heatmap\" class=\"m-2 p-5\"></div><!-- <div id=\"legend\"></div> --></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = initHeatmap(countsByDay).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func initHeatmap(countsByDay []types.CountByDay) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_initHeatmap_acad`,
		Function: `function __templ_initHeatmap_acad(countsByDay){// let countsByDay = [
    //     { date: "2024-01-01T00:00:00Z", value: 1 },
    //     { date: "2024-03-02T00:00:00Z", value: 6 },
    //     { date: "2024-04-02T00:00:00Z", value: 16 },
    //     { date: "2024-04-03T00:00:00Z", value: 9 },
    //     { date: "2024-04-04T00:00:00Z", value: 9 },
    // ];

    // dayjs().localeData();

    function getScreenSize() {
        const breakpoints = {
        sm: 640,
        md: 768,
        lg: 1024,
        xl: 1280,
        "2xl": 1536,
        };
        const width = window.innerWidth;

        if (width < breakpoints.sm) {
        return "small";
        } else if (width < breakpoints.md) {
        return "medium";
        } else if (width < breakpoints.lg) {
        return "large";
        } else {
        return "extralarge";
        }
    }

    let screenSize = getScreenSize();
    let size = {
        small: {
        subtract: 3,
        range: 4,
        },
        medium: {
        subtract: 4,
        range: 5,
        },
        large: {
        subtract: 5,
        range: 6,
        },
        extralarge: {
        subtract: 6,
        range: 7,
        },
    };
    let currentSize = size[screenSize];

    function cleanUpCountsByDay(counts) {
        return counts.map((item) => ({
        date: dayjs(item.date).format("YYYY-MM-DD"),
        value: item.value,
        }));
    }

    countsByDay = cleanUpCountsByDay(countsByDay);

    let start = dayjs().subtract(currentSize.subtract, "month");

    const upToTodayTemplate = function (DateHelper) {
        return {
        name: "ghDayUpToToday",
        parent: "ghDay",

        mapping: (startTimestamp, endTimestamp) => {
            let weekNumber = 0;
            let x = -1;

            return DateHelper.intervals(
            "day",
            startTimestamp,
            DateHelper.date(endTimestamp)
            )
            .map((ts) => {
                const date = DateHelper.date(ts);

                today = new Date();
                if (date > today) {
                return null;
                }

                if (weekNumber !== date.week()) {
                weekNumber = date.week();
                x += 1;
                }

                return {
                t: ts,
                x,
                y: date.day(),
                };
            })
            .filter((n) => n !== null);
        },
        };
    };

    const cal = new CalHeatmap();
    cal.addTemplates(upToTodayTemplate);

    function paintHeatmap(theme) {
        cal.paint(
        {
            data: { source: countsByDay, x: "date", y: "value" },
            range: currentSize.range,
            date: { start: start, max: new Date() },
            domain: {
            type: "month",
            gutter: 10,
            dynamicDimension: true,
            label: { position: "top" },
            },
            subDomain: {
            type: "ghDayUpToToday",
            radius: 3,
            width: 15,
            height: 15,
            gutter: 4,
            },
            scale: {
            color: {
                type: "linear",
                // More schemes at https://observablehq.com/@d3/color-schemes
                scheme: "Greens",
                domain: [0, 3],
            },
            },

            theme: theme,
        },
        [
            [
            Tooltip,
            {
                text: function (date, value, dayjsDate) {
                return (
                    (value ? value : "No") +
                    " interactions on " +
                    dayjsDate.format("dddd, MMMM D, YYYY")
                );
                },
            },
            ],
            [
            Legend,
            {
                tickSize: 0,
                width: 100,
                itemSelector: "#legend",
                label: "",
            },
            ],
            [
            CalendarLabel,
            {
                width: 30,
                padding: [24, 0, 0, 0],
                textAlign: "start",
                text: () =>
                dayjs.weekdaysShort().map((d, i) => (i % 2 == 0 ? "" : d)),
            },
            ],
        ]
        );
    }

    function getLightOrDarkTheme() {
        let siteTheme = document.documentElement.getAttribute("data-theme");
        if (siteTheme == "lightmode") {
        return "light";
        } else {
        return "dark";
        }
    }

    paintHeatmap(getLightOrDarkTheme());   
}`,
		Call:       templ.SafeScript(`__templ_initHeatmap_acad`, countsByDay),
		CallInline: templ.SafeScriptInline(`__templ_initHeatmap_acad`, countsByDay),
	}
}

var _ = templruntime.GeneratedTemplate
